language: python

sudo: true

before_install:
    - echo "deb http://cran.rstudio.com/bin/linux/ubuntu precise/" >> /etc/apt/sources.list 
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
    - sudo add-apt-repository ppa:marutter/rdev
    - sudo apt-get update
    - sudo apt-get upgrade
    - sudo apt-get install r-base r-base-dev 

install:
    - pip install .
