language: python

sudo: true

before_install:
    - echo 'deb http://cran.rstudio.com/bin/linux/ubuntu precise/' | sudo tee --append /etc/apt/sources.list > /dev/null
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
    - sudo apt-get update
    - sudo apt-get install r-base r-base-dev 

install:
    - pip install .
